[project]
name = "nfelo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.10.0",
    "numpy>=1.21.2",
    "pandas>=1.3.2",
    "requests>=2.22.0",
    "statsmodels>=0.12.2",
]

